### DISCUSSION TITLE
Multiple tabulators with different styling

### DISCUSSION THREAD

**Discussion by meatballs** [anvilistas/tabulator#131] [Q&A] [answered]
Anyone got any thoughts on how to use multiple tabulators within an app but with different css styles applied?

Is there perhaps some way to add a consistent class to a table, row, cell and then use that class within my app's `theme.css`?

**Comment by s-cork** [comment, marked as answer]
Tabulator is just an HtmlTemplate
do you want a role property?

You can then combine it with the css selectors as defined here:
https://tabulator.info/docs/5.5/style#css

**Reply by s-cork** [reply]
and looks like `role` is already a property - so yeah just combine a role with those css selectors and should work

**Reply by s-cork** [reply]
You can find examples here:
https://github.com/olifolkerd/tabulator/tree/master/dist/css

**Reply by meatballs** [reply]
Excellent! Thank you. I suspected it was worth asking rather than banging my head!

**Reply by meatballs** [reply]
hmmm... I've tried creating a role and assigning that to a tabulator, but I don't see it appearing as a class anywhere within the dom

**Reply by s-cork** [reply]
oh wierd hold on

**Reply by s-cork** [reply]
Ok i've pushed a change and bumped the version
try now

**Reply by meatballs** [reply]
Yep! That's done the job!

**Reply by meatballs** [reply]
I'd tried this as one of my attempts but assumed I was doing something wrong. Glad I asked! Many thanks for the change.

**Reply by s-cork** [reply]
Yeah - I guess no one has ever used a role before!

**Comment by antletem** [comment]
This was a very helpful post!

and just to add a bit more to it.

Here is a role I have for my tables to give them curved edges and a rule for selected rows:

```css
.anvil-role-tabulator-base {
  border-radius: 10px;
  /* Adjust the value to change the curvature */
  padding: 5px;
}

.anvil-role-tabulator-base .tabulator-selected {
  background-color: %color:Primary Container%  !important;
  color: %color:On Primary Container% !important;
}
```

Just because I was still having difficulties with implementation.
